#![feature(test)]

extern crate bioinformatics_algorithms;
extern crate test;

use bioinformatics_algorithms::alignment::*;

const s1:&str = "ACAATCCGGTACTAGCTAGCTAGCGCGTTGCGTAAAGTCCGTTAGCCAAATGGAAATTTCCCGGGCGCGTATAATGCATGCATGCATGCATGCATTTTTTGGGGGGCCCCCCCTAGCATCGACTACGATCAGCTACGACTCGATCAGCTACGACTAGCATCGACTACGCTACGATCCGAGTCAGCTAGCTAGCATCGATCGACTACGACTCAGATCGATCGATCACGTCAGCTACTACAGTCAGCTACGCTAGCTACGCTAGCTACGTCAGCTACGTATAGATCAGCTCCGATCAGCGATCAGCTCAGCTACGACTGCTACGATCGACTACGTCGACTAGCTACGCTAGCTACGCTACGCTACGTCAGCTACGACTCTTTTAGCGGCTATGCATTCACGGCGGATGGCATGCGATGCGATTCGGGCATTGCATTCTAGGCTAGCGATCGCATCTGGCGTACTACTCACGAGCTACGGCGATCACGACATGCATCTGCATCGACTCCACTCGACTACGACAGTATGCATCAGCTCTCTCACGACTGCAT";

const s2: &str = "AGCATGCTGCCTGTAATGCATCAAACGCTAGCTAGCATCGATCAAATTTCCCGGGCGCGTATATAGCTAGCATCGATAGCATCAGCTTATTTGGCGGGCCACCCGCATCGACTACGATCGCTACGACTCGATCAGCTCAGCATCGACTACGCATCGTACGACTGCTCATCGACATCTCTCAGCTTAGCATCGAGACTACGACTGATCGATCGAGTCAGCTACTACGCTAGCTACGTCACAGTCAGCTACGCTAGCTACGCTAGCTACGTCACTACGGATCAGCCGATCGCGATCGCATGATCAGCTCAGCTACGACTGCTACCGACTACGTCGACTAGCTACGCTAGCTACGCGCTACGTCAGCTACGTAGCGGCTATGCATTCAGGATGGCATGCGATGCGATTCGGGCATTTCTAGGCTAGCGACGATGCTCGAGCTATTCGACTCGCATCTGACGCGTACTACTCACGAGCTACGGCGATCAGCTACGACTGCATCGACTCGCATCACTCGACTACGACTCGCTCTCTCAGCGATCGATGTCAGT";
const gap: char = '-';

#[cfg(test)]
mod tests {
    use super::*;
    use test::Bencher;

    #[bench]
    fn bench_needleman1(b: &mut Bencher) {
        b.iter(|| {
            needleman_wunsch_1::needleman_wunsch(s1, s2, gap);
        });
    }
    #[bench]
    fn bench_needleman(b: &mut Bencher) {
        b.iter(|| {
            needleman_wunsch::needleman_wunsch(s1, s2, gap);
        });
    }
}
